# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77268be81684c816ec6048e608ed367c9e3373776f907affcfc03c58d978c0702dcd564333a1e96b1ef79413120e3b91127e526fa868ea626c80b63d60336940

test:
  secret_key_base: 5a820144b7edea7debad3cadc134ed1a19a7f588167f5cbe58d5a87cd259a7295acc6680548a1aa29d517d50bc5f5637578f96a30b0749231dadfff04893f9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
